theme: jekyll-theme-tactile
title: Welcome to Shaurya's Homepage!
description: this is my personal website, where I'll be posting all of my blog posts, life updates, and any content that I find interesting. 
